### ISSUE TITLE
Add fallback for x-rateliimt-reset

### ISSUE THREAD

**Issue by gal-legit** [gofri/go-github-ratelimit#6]
The API documentation states that the `x-ratelimit-reset` header should be used for secondary rate limits if the `Retry-After` header is missing.
Although in practice I only encountered this header for the primary rate limits, let's just follow the guidelines.
https://docs.github.com/en/rest/guides/best-practices-for-integrators?apiVersion=2022-11-28#dealing-with-secondary-rate-limits

**Comment by gofri** [comment]
Closing, #9 is an actual reproduction with all the relevant info.
